# Generated by Django 3.0.7 on 2020-06-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200629_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
