# Generated by Django 3.0.7 on 2020-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200630_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
