# Generated by Django 3.0.7 on 2020-07-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_link_votes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='votes_total',
            field=models.IntegerField(default=0),
        ),
    ]
