# Generated by Django 3.0.7 on 2020-07-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
