# Generated by Django 3.0.7 on 2020-07-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_comment_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Link'),
        ),
    ]
